version: "3.8"

services:
  python-flask-app-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-flask-app-container
    ports:
      - 5002:5000
    volumes:
      - ./:/app
    networks:
      - mysql-python-app-network

  mysql-flask-app-container:
    image: mysql:8.0.28
    container_name: mysql-flask-app-container
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=nemesys123
    volumes:
      - mysql-python-app-volume:/var/lib/mysql
      - mysql-python-app-volume-config:/etc/mysql
    networks:
      - mysql-python-app-network

networks:
  mysql-python-app-network:
    name: mysql-python-app-network
volumes:
  mysql-python-app-volume:
  mysql-python-app-volume-config:
