version: "3.8"

services:
  python-flask-app-container:
    image: sunlight4d/python-flask-app:v1.0.0
    container_name: python-flask-app-container
    ports:
      - 5002:5000
    volumes:
      - ./:/app
    networks:
      - mysql-python-app-network

  # nginx service
  nginx:
    # The official Nginx Docker from Docker Hub. For building the Nginx container
    image: nginx:latest
    volumes:
      # Volume for the nginx Docker container
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # The Nginx service depends on the Flask application service (It will link the Flask web application and Nginx Load balancer)
    depends_on:
      - app
    # ports for the Nginx application service
    ports:
      # Port for the Nginx load balancer
      - "80:80"

  mysql-flask-app-container:
    image: mysql:8.0.28
    container_name: mysql-flask-app-container
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=nemesys123
    volumes:
      - mysql-python-app-volume:/var/lib/mysql
      - mysql-python-app-volume-config:/etc/mysql
    networks:
      - mysql-python-app-network

networks:
  mysql-python-app-network:
    name: mysql-python-app-network
volumes:
  mysql-python-app-volume:
  mysql-python-app-volume-config:
