from sqlalchemy import Column, Integer, String,create_engine, ForeignKey
from .database import Base

class CoalYard(Base):
    __tablename__ = 'tbl_coal_yard'
    id = Column(Integer, primary_key =  True)
    OUTBAR_ID = Column(Integer)
    ORG_ID_SUPPLIER = Column(Integer)
    id_sumber_tambang = Column(Integer,ForeignKey("tbl_sumber_tambang.id"))
    VESSEL_ID = Column(String)
    VESSEL = Column(String)
    CALORIE_ID = Column(Integer)
    CALORIE = Column(Integer)
    VOLUME = Column(String)
    TA = Column(String)
    CALORIE_LAB = Column(Integer)
    ORG_ID = Column(String)
    ORG_CODE = Column(String)
    BRAND_NAME = Column(String)
    STATUS = Column(String)
    VOLUME_LOAD = Column(String)
    AREA_ID = Column(String)
    AREA = Column(String)
    LOC_ID = Column(String)
    LOCATION = Column(String)
    LAYER_ID = Column(String)
    LAYER = Column(String)
    LOAD_DATE = Column(String)
    LAMA_HARI = Column(Integer)
    GRP = Column(String)
    RECLAIM_DATE = Column(String)
    FLOWRATE = Column(String)
    DURATION = Column(String)
    STACKING_ID = Column(String)
    URUT = Column(Integer)
    VOLUME_SISA_RECLAIM = Column(String)
    VOLUME_RECLAIM = Column(String)
    RECLAIM_ID = Column(Integer)
    OUTBAR_DATE = Column(String)